services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: progress-hub-db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Progress!Hub1"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - progress_hub_mssql:/var/opt/mssql

volumes:
  progress_hub_mssql:
